services:
  www:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_ejm1
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: user1.pa55
    volumes:
      - ./base_datos:/docker-entrypoint-initdb.d  # Scripts SQL se ejecutan al iniciar
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin.pa55