services:
  www:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/
    depends_on:
      - db
  db:
    image: postgres:latest
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ricurasAltas
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: user1.pa55
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin.pa55